on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - name: Install Node
              uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Pack
              run: cd types/three && npm pack | xargs -I {} mv {} ../../package.tgz
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: package.tgz
